slurmstepd: error: *** JOB 28743309 ON n0272.lr6 CANCELLED AT 2021-02-04T17:28:15 ***
/global/home/users/kalatimer/proj/20supersat/src/revmywrf/ss_qss_calculations.py:72: RuntimeWarning: invalid value encountered in true_divide
  return meanr/nconc
allpts Polluted
allpts Unpolluted
Traceback (most recent call last):
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/FINAL_bipanel_ss_qss_vs_z_figsrc.py", line 265, in <module>
    main()
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/FINAL_bipanel_ss_qss_vs_z_figsrc.py", line 59, in main
    z_dict['up10perc'], z_bins_dict, colors_arr[7], 'up10perc')
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/FINAL_bipanel_ss_qss_vs_z_figsrc.py", line 121, in make_and_save_bipanel_ss_qss_vs_z
    ax1 = plot_fan_ss(ax1)
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/FINAL_bipanel_ss_qss_vs_z_figsrc.py", line 200, in plot_fan_ss
    with open(DATA_DIR + 'fan_ss_' + profile_filename + '.csv', 'r') as readFile:
FileNotFoundError: [Errno 2] No such file or directory: '/clusterfs/stratus/dromps/wrf_fan2018/Supersaturation/Supersaturation/fan_ss_deep_poll.csv'
/global/home/users/kalatimer/proj/20supersat/src/revmywrf/ss_qss_calculations.py:72: RuntimeWarning: invalid value encountered in true_divide
  return meanr/nconc
allpts Polluted
allpts Unpolluted
Traceback (most recent call last):
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/FINAL_bipanel_ss_qss_vs_z_figsrc.py", line 266, in <module>
    main()
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/FINAL_bipanel_ss_qss_vs_z_figsrc.py", line 60, in main
    z_dict['up10perc'], z_bins_dict, colors_arr[7], 'up10perc')
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/FINAL_bipanel_ss_qss_vs_z_figsrc.py", line 122, in make_and_save_bipanel_ss_qss_vs_z
    ax1 = plot_fan_ss(ax1)
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/FINAL_bipanel_ss_qss_vs_z_figsrc.py", line 201, in plot_fan_ss
    with open(CSV_DATA_DIR + 'fan_ss_' + profile_filename + '.csv', 'r') as readFile:
FileNotFoundError: [Errno 2] No such file or directory: '/global/home/users/kalatimer/proj/20supersat/revmywrf/data/fan_ss_deep_poll.csv'
/global/home/users/kalatimer/proj/20supersat/src/revmywrf/ss_qss_calculations.py:72: RuntimeWarning: invalid value encountered in true_divide
  return meanr/nconc
allpts Polluted
allpts Unpolluted
Traceback (most recent call last):
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/FINAL_bipanel_ss_qss_vs_z_figsrc.py", line 266, in <module>
    main()
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/FINAL_bipanel_ss_qss_vs_z_figsrc.py", line 60, in main
    z_dict['up10perc'], z_bins_dict, colors_arr[7], 'up10perc')
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/FINAL_bipanel_ss_qss_vs_z_figsrc.py", line 122, in make_and_save_bipanel_ss_qss_vs_z
    ax1 = plot_fan_ss(ax1)
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/FINAL_bipanel_ss_qss_vs_z_figsrc.py", line 201, in plot_fan_ss
    with open(CSV_DATA_DIR + 'fan_ss_' + profile_filename + '.csv', 'r') as readFile:
FileNotFoundError: [Errno 2] No such file or directory: '/global/home/users/kalatimer/proj/20supersat/data/revmywrf/fan_ss_deep_poll.csv'
/global/home/users/kalatimer/proj/20supersat/src/revmywrf/ss_qss_calculations.py:72: RuntimeWarning: invalid value encountered in true_divide
  return meanr/nconc
allpts Polluted
allpts Unpolluted
Traceback (most recent call last):
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/FINAL_bipanel_ss_qss_vs_z_figsrc.py", line 266, in <module>
    main()
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/FINAL_bipanel_ss_qss_vs_z_figsrc.py", line 60, in main
    z_dict['up10perc'], z_bins_dict, colors_arr[7], 'up10perc')
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/FINAL_bipanel_ss_qss_vs_z_figsrc.py", line 122, in make_and_save_bipanel_ss_qss_vs_z
    ax1 = plot_fan_ss(ax1)
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/FINAL_bipanel_ss_qss_vs_z_figsrc.py", line 202, in plot_fan_ss
    csvreader = csv.reader(readFile, \
NameError: name 'csv' is not defined
/global/home/users/kalatimer/proj/20supersat/src/revmywrf/ss_qss_calculations.py:72: RuntimeWarning: invalid value encountered in true_divide
  return meanr/nconc
allpts Polluted
allpts Unpolluted
up10perc Polluted
up10perc Unpolluted
/global/home/users/kalatimer/proj/20supersat/src/revmywrf/ss_qss_calculations.py:72: RuntimeWarning: invalid value encountered in true_divide
  return meanr/nconc
allpts Polluted
allpts Unpolluted
Traceback (most recent call last):
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/FINAL_bipanel_ss_qss_vs_z_figsrc.py", line 274, in <module>
    main()
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/FINAL_bipanel_ss_qss_vs_z_figsrc.py", line 61, in main
    z_dict['up10perc'], z_bins_dict, colors_arr[7], 'up10perc')
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/FINAL_bipanel_ss_qss_vs_z_figsrc.py", line 123, in make_and_save_bipanel_ss_qss_vs_z
    ax1 = plot_fan_ss(ax1)
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/FINAL_bipanel_ss_qss_vs_z_figsrc.py", line 217, in plot_fan_ss
    label=profile_labels[i])
  File "/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 1665, in plot
    lines = [*self._get_lines(*args, data=data, **kwargs)]
  File "/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 225, in __call__
    yield from self._plot_args(this, kwargs)
  File "/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 391, in _plot_args
    x, y = self._xy_from_xy(x, y)
  File "/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 270, in _xy_from_xy
    "have shapes {} and {}".format(x.shape, y.shape))
ValueError: x and y must have same first dimension, but have shapes (2000,) and (2,)
/global/home/users/kalatimer/proj/20supersat/src/revmywrf/ss_qss_calculations.py:72: RuntimeWarning: invalid value encountered in true_divide
  return meanr/nconc
allpts Polluted
allpts Unpolluted
up10perc Polluted
up10perc Unpolluted
/global/home/users/kalatimer/proj/20supersat/src/revmywrf/ss_qss_calculations.py:72: RuntimeWarning: invalid value encountered in true_divide
  return meanr/nconc
allpts Polluted
allpts Unpolluted
up10perc Polluted
up10perc Unpolluted
/global/home/users/kalatimer/proj/20supersat/src/revmywrf/ss_qss_calculations.py:72: RuntimeWarning: invalid value encountered in true_divide
  return meanr/nconc
allpts Polluted
allpts Unpolluted
up10perc Polluted
up10perc Unpolluted
/global/home/users/kalatimer/proj/20supersat/src/revmywrf/ss_qss_calculations.py:72: RuntimeWarning: invalid value encountered in true_divide
  return meanr/nconc
up10perc Polluted
up10perc Unpolluted
/global/home/users/kalatimer/proj/20supersat/src/revmywrf/ss_qss_calculations.py:72: RuntimeWarning: invalid value encountered in true_divide
  return meanr/nconc
up10perc Polluted
up10perc Unpolluted
