Traceback (most recent call last):
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/newfilt_heatmap_ss_qss_vs_ss_wrf_figsrc.py", line 194, in <module>
    main()
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/newfilt_heatmap_ss_qss_vs_ss_wrf_figsrc.py", line 40, in main
    incl_vent, versionstr)
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/newfilt_heatmap_ss_qss_vs_ss_wrf_figsrc.py", line 61, in make_and_save_ss_qss_vs_ss_wrf
    qvstar = get_qvstar(temp, pres)
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/newfilt_heatmap_ss_qss_vs_ss_wrf_figsrc.py", line 128, in get_qvstar
    return e_sat/pres*R_a/R_v
NameError: name 'R_a' is not defined
/global/home/users/kalatimer/proj/20supersat/src/revmywrf/ss_qss_calculations.py:72: RuntimeWarning: invalid value encountered in true_divide
  return meanr/nconc
/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3335: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in true_divide
  ret = ret.dtype.type(ret / rcount)
/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/numpy/lib/function_base.py:393: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis)
/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/numpy/core/_methods.py:154: RuntimeWarning: invalid value encountered in true_divide
  ret, rcount, out=ret, casting='unsafe', subok=False)
/global/home/users/kalatimer/proj/20supersat/src/revmywrf/ss_qss_calculations.py:162: RuntimeWarning: Degrees of freedom <= 0 for slice
  ssxm, ssxym, ssyxm, ssym = np.cov(x, y, bias=1).flat
/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/numpy/lib/function_base.py:2455: RuntimeWarning: divide by zero encountered in true_divide
  c *= np.true_divide(1, fact)
/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/numpy/lib/function_base.py:2455: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)
nan nan nan
Polluted
# pts total: 0
Traceback (most recent call last):
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/newfilt_heatmap_ss_qss_vs_ss_wrf_figsrc.py", line 210, in <module>
    main()
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/newfilt_heatmap_ss_qss_vs_ss_wrf_figsrc.py", line 56, in main
    incl_vent, versionstr)
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/newfilt_heatmap_ss_qss_vs_ss_wrf_figsrc.py", line 105, in make_and_save_ss_qss_vs_ss_wrf
    print('max: ' + str(np.nanmax(ss_qss)))
  File "<__array_function__ internals>", line 6, in nanmax
  File "/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/numpy/lib/nanfunctions.py", line 443, in nanmax
    res = np.amax(a, axis=axis, out=out, **kwargs)
  File "<__array_function__ internals>", line 6, in amax
  File "/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2668, in amax
    keepdims=keepdims, initial=initial, where=where)
  File "/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 88, in _wrapreduction
    return reduction(axis=axis, out=out, **passkwargs)
  File "/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/numpy/ma/core.py", line 5807, in max
    axis=axis, out=out, **kwargs).view(type(self))
  File "/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/numpy/core/_methods.py", line 30, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation maximum which has no identity
/global/home/users/kalatimer/proj/20supersat/src/revmywrf/ss_qss_calculations.py:72: RuntimeWarning: invalid value encountered in true_divide
  return meanr/nconc
/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3335: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in true_divide
  ret = ret.dtype.type(ret / rcount)
/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/numpy/lib/function_base.py:393: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis)
/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/numpy/core/_methods.py:154: RuntimeWarning: invalid value encountered in true_divide
  ret, rcount, out=ret, casting='unsafe', subok=False)
/global/home/users/kalatimer/proj/20supersat/src/revmywrf/ss_qss_calculations.py:162: RuntimeWarning: Degrees of freedom <= 0 for slice
  ssxm, ssxym, ssyxm, ssym = np.cov(x, y, bias=1).flat
/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/numpy/lib/function_base.py:2455: RuntimeWarning: divide by zero encountered in true_divide
  c *= np.true_divide(1, fact)
/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/numpy/lib/function_base.py:2455: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)
(84, 66, 450, 450)
0
nan nan nan
Polluted
# pts total: 0
Traceback (most recent call last):
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/newfilt_heatmap_ss_qss_vs_ss_wrf_figsrc.py", line 213, in <module>
    main()
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/newfilt_heatmap_ss_qss_vs_ss_wrf_figsrc.py", line 56, in main
    incl_vent, versionstr)
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/newfilt_heatmap_ss_qss_vs_ss_wrf_figsrc.py", line 108, in make_and_save_ss_qss_vs_ss_wrf
    print('max: ' + str(np.nanmax(ss_qss)))
  File "<__array_function__ internals>", line 6, in nanmax
  File "/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/numpy/lib/nanfunctions.py", line 443, in nanmax
    res = np.amax(a, axis=axis, out=out, **kwargs)
  File "<__array_function__ internals>", line 6, in amax
  File "/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2668, in amax
    keepdims=keepdims, initial=initial, where=where)
  File "/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 88, in _wrapreduction
    return reduction(axis=axis, out=out, **passkwargs)
  File "/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/numpy/ma/core.py", line 5807, in max
    axis=axis, out=out, **kwargs).view(type(self))
  File "/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/numpy/core/_methods.py", line 30, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation maximum which has no identity
/global/home/users/kalatimer/proj/20supersat/src/revmywrf/ss_qss_calculations.py:72: RuntimeWarning: invalid value encountered in true_divide
  return meanr/nconc
/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3335: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in true_divide
  ret = ret.dtype.type(ret / rcount)
/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/numpy/lib/function_base.py:393: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis)
/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/numpy/core/_methods.py:154: RuntimeWarning: invalid value encountered in true_divide
  ret, rcount, out=ret, casting='unsafe', subok=False)
/global/home/users/kalatimer/proj/20supersat/src/revmywrf/ss_qss_calculations.py:162: RuntimeWarning: Degrees of freedom <= 0 for slice
  ssxm, ssxym, ssyxm, ssym = np.cov(x, y, bias=1).flat
/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/numpy/lib/function_base.py:2455: RuntimeWarning: divide by zero encountered in true_divide
  c *= np.true_divide(1, fact)
/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/numpy/lib/function_base.py:2455: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)
66998716.0
59092372.0
39736510.0
3855041.5
(84, 66, 450, 450)
0
nan nan nan
Polluted
# pts total: 0
Traceback (most recent call last):
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/newfilt_heatmap_ss_qss_vs_ss_wrf_figsrc.py", line 217, in <module>
    main()
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/newfilt_heatmap_ss_qss_vs_ss_wrf_figsrc.py", line 56, in main
    incl_vent, versionstr)
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/newfilt_heatmap_ss_qss_vs_ss_wrf_figsrc.py", line 112, in make_and_save_ss_qss_vs_ss_wrf
    print('max: ' + str(np.nanmax(ss_qss)))
  File "<__array_function__ internals>", line 6, in nanmax
  File "/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/numpy/lib/nanfunctions.py", line 443, in nanmax
    res = np.amax(a, axis=axis, out=out, **kwargs)
  File "<__array_function__ internals>", line 6, in amax
  File "/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2668, in amax
    keepdims=keepdims, initial=initial, where=where)
  File "/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 88, in _wrapreduction
    return reduction(axis=axis, out=out, **passkwargs)
  File "/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/numpy/ma/core.py", line 5807, in max
    axis=axis, out=out, **kwargs).view(type(self))
  File "/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/numpy/core/_methods.py", line 30, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation maximum which has no identity
/global/home/users/kalatimer/proj/20supersat/src/revmywrf/ss_qss_calculations.py:72: RuntimeWarning: invalid value encountered in true_divide
  return meanr/nconc
/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/matplotlib/colors.py:1110: RuntimeWarning: invalid value encountered in less_equal
  mask |= resdat <= 0
/global/home/users/kalatimer/proj/20supersat/src/revmywrf/ss_qss_calculations.py:72: RuntimeWarning: invalid value encountered in true_divide
  return meanr/nconc
/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/matplotlib/colors.py:1110: RuntimeWarning: invalid value encountered in less_equal
  mask |= resdat <= 0
(84, 66, 450, 450)
2950497
0.8830381666092544 -0.012647732028059355 0.9135522585953241
Polluted
# pts total: 2950497
max: 20.411121523993486
# pts ss > 2%: 428300
Number of points in Q1: 2946891
Number of points in Q2: 0
Number of points in Q3: 0
Number of points in Q4: 3231

Domain: 0.18117489883201776 20.411121523993486
Range: -3.168922 20.070312
(84, 66, 450, 450)
2063630
0.8228402101718227 0.00893120325525909 0.8820584205309852
Unpolluted
# pts total: 2063630
max: 7.99157325765308
# pts ss > 2%: 132993
Number of points in Q1: 2060932
Number of points in Q2: 0
Number of points in Q3: 0
Number of points in Q4: 2354

Domain: 0.19436614236065888 7.99157325765308
Range: -4.1184945 12.127304
/global/home/users/kalatimer/proj/20supersat/src/revmywrf/ss_qss_calculations.py:72: RuntimeWarning: invalid value encountered in true_divide
  return meanr/nconc
/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/matplotlib/colors.py:1110: RuntimeWarning: invalid value encountered in less_equal
  mask |= resdat <= 0
/global/home/users/kalatimer/proj/20supersat/src/revmywrf/ss_qss_calculations.py:72: RuntimeWarning: invalid value encountered in true_divide
  return meanr/nconc
/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/matplotlib/colors.py:1110: RuntimeWarning: invalid value encountered in less_equal
  mask |= resdat <= 0
(84, 66, 450, 450)
3340319
0.8067639005750012 0.08198887513169506 0.8835764448340262
Polluted
# pts total: 3340319
max: 27.870919055851296
# pts ss > 2%: 764668
Number of points in Q1: 3334044
Number of points in Q2: 0
Number of points in Q3: 0
Number of points in Q4: 5899

Domain: 0.18117489443775012 27.870919055851296
Range: -9.126421 20.070312
(84, 66, 450, 450)
2705968
0.7733306134414968 0.08076294285868157 0.9120574126883049
Unpolluted
# pts total: 2705968
max: 45.558524915137916
# pts ss > 2%: 756932
Number of points in Q1: 2702382
Number of points in Q2: 0
Number of points in Q3: 0
Number of points in Q4: 3240

Domain: 0.19436614179356138 45.558524915137916
Range: -10.896954 31.37943
