/global/home/users/kalatimer/proj/20supersat/src/revmywrf/ss_qss_calculations.py:72: RuntimeWarning: invalid value encountered in true_divide
  return meanr/nconc
Traceback (most recent call last):
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/ss_mean_only_systematic_filtering_evaluation.py", line 154, in <module>
    main()
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/ss_mean_only_systematic_filtering_evaluation.py", line 54, in main
    make_and_save_ss_mean_heatmap(ss_qss_mean_arr, \
NameError: name 'make_and_save_ss_mean_heatmap' is not defined
/global/home/users/kalatimer/proj/20supersat/src/revmywrf/ss_qss_calculations.py:72: RuntimeWarning: invalid value encountered in true_divide
  return meanr/nconc
Traceback (most recent call last):
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/ss_mean_only_systematic_filtering_evaluation.py", line 154, in <module>
    main()
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/ss_mean_only_systematic_filtering_evaluation.py", line 55, in main
    ss_wrf_mean_arr, case_label)
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/ss_mean_only_systematic_filtering_evaluation.py", line 125, in make_and_save_ss_mean_heatmap
    im1 = ax1.imshow(ss_qss_mean_arr, cmap=rev_magma)
NameError: name 'ax1' is not defined
/global/home/users/kalatimer/proj/20supersat/src/revmywrf/ss_qss_calculations.py:72: RuntimeWarning: invalid value encountered in true_divide
  return meanr/nconc
Traceback (most recent call last):
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/ss_mean_only_systematic_filtering_evaluation.py", line 154, in <module>
    main()
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/ss_mean_only_systematic_filtering_evaluation.py", line 55, in main
    ss_wrf_mean_arr, case_label)
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/ss_mean_only_systematic_filtering_evaluation.py", line 143, in make_and_save_ss_mean_heatmap
    ax2.set_xticklabels(np.around(np.log20(lwc_filter_vals), 2))
  File "/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/numpy/__init__.py", line 220, in __getattr__
    "{!r}".format(__name__, attr))
AttributeError: module 'numpy' has no attribute 'log20'
/global/home/users/kalatimer/proj/20supersat/src/revmywrf/ss_qss_calculations.py:72: RuntimeWarning: invalid value encountered in true_divide
  return meanr/nconc
