Traceback (most recent call last):
  File "/global/home/users/kalatimer/proj/20supersat/src/wrf/random_bin_check.py", line 99, in <module>
    main()
  File "/global/home/users/kalatimer/proj/20supersat/src/wrf/random_bin_check.py", line 40, in main
    bin_nconc = get_bin_nconc_slice(random_bin_ind, case_label, z_lim)
  File "/global/home/users/kalatimer/proj/20supersat/src/wrf/random_bin_check.py", line 50, in get_bin_nconc_slice
    met_file = Dataset(DATA_DIR + case_dir_name + \
NameError: name 'Dataset' is not defined
Traceback (most recent call last):
  File "/global/home/users/kalatimer/proj/20supersat/src/wrf/random_bin_check.py", line 100, in <module>
    main()
  File "/global/home/users/kalatimer/proj/20supersat/src/wrf/random_bin_check.py", line 41, in main
    bin_nconc = get_bin_nconc_slice(random_bin_ind, case_label, z_lim)
  File "/global/home/users/kalatimer/proj/20supersat/src/wrf/random_bin_check.py", line 70, in get_bin_nconc_slice
    range(len(sigma_coeffs))])*1.e-3
NameError: name 'sigma_coeffs' is not defined
Polluted (1000, 1500) 15 6.4e-05 0.13796169483653456
Polluted (3000, 4000) 15 6.4e-05 1.4724885397958276
Unpolluted (1000, 1500) 15 6.4e-05 0.17669417287280093
Unpolluted (3000, 4000) 15 6.4e-05 12.852174387028766
