Traceback (most recent call last):
  File "/global/home/users/kalatimer/proj/20supersat/src/wrf/subdom_ss_pred_vs_z_figsrc.py", line 235, in <module>
    main()
  File "/global/home/users/kalatimer/proj/20supersat/src/wrf/subdom_ss_pred_vs_z_figsrc.py", line 43, in main
    get_ss_pred_and_z_data(case_filtered_data_dict)
  File "/global/home/users/kalatimer/proj/20supersat/src/wrf/subdom_ss_pred_vs_z_figsrc.py", line 60, in get_ss_pred_and_z_data
    lon = x*180./np.pi*1./R_e
NameError: name 'R_e' is not defined
Traceback (most recent call last):
  File "/global/home/users/kalatimer/proj/20supersat/src/wrf/subdom_ss_pred_vs_z_figsrc.py", line 241, in <module>
    main()
  File "/global/home/users/kalatimer/proj/20supersat/src/wrf/subdom_ss_pred_vs_z_figsrc.py", line 57, in main
    make_and_save_ss_pred_vs_z(ss_pred_dict, z_dict, z_bins_dict)
  File "/global/home/users/kalatimer/proj/20supersat/src/wrf/subdom_ss_pred_vs_z_figsrc.py", line 93, in make_and_save_ss_pred_vs_z
    shared_z_lims = get_shared_z_lims(z_dict, z_bins_dict)
  File "/global/home/users/kalatimer/proj/20supersat/src/wrf/subdom_ss_pred_vs_z_figsrc.py", line 166, in get_shared_z_lims
    z_lims.append(get_z_lim(area_frac, z_bins))
  File "/global/home/users/kalatimer/proj/20supersat/src/wrf/subdom_ss_pred_vs_z_figsrc.py", line 176, in get_z_lim
    while area_frac[i] < area_frac_cutoff:
IndexError: index 48 is out of bounds for axis 0 with size 48
Traceback (most recent call last):
  File "/global/home/users/kalatimer/proj/20supersat/src/wrf/subdom_ss_pred_vs_z_figsrc.py", line 220, in <module>
    main()
  File "/global/home/users/kalatimer/proj/20supersat/src/wrf/subdom_ss_pred_vs_z_figsrc.py", line 57, in main
    make_and_save_ss_pred_vs_z(ss_pred_dict, z_dict, z_bins_dict)
  File "/global/home/users/kalatimer/proj/20supersat/src/wrf/subdom_ss_pred_vs_z_figsrc.py", line 129, in make_and_save_ss_pred_vs_z
    ax_arr[i].set_ylim(z_lim)
NameError: name 'z_lim' is not defined
